name: CommandSystem
main: de.minestar.maventest.MavenTestCore
version: ${pom.version}
depend: [MineStarLibrary]
commands:
  warp:
    description: Remove a protection
    usage: /warp
  tr:
    description: Remove a protection
    usage: /tr
  normal:
    description: Get some information about a protection
    usage: /normal
  cli:
    description: Get some information about a protection
    usage: /normal
  flash:
    description: Get some information about a protection
    usage: /normal